### ISSUE TITLE
Not an issue but questions 

### ISSUE THREAD

**Issue by simon88** [polihedron/Seeed-LoRa-E5_peer2peer#1]
Hi, 
First of all thanks for your job I’m really interested to use your code. Do you have a schematic just to show what’s pin are used for lcd spi for example? And last question you code is like a ping pong application I’m right you don’t use lorawan gateway ?

**Comment by polihedron** [comment]
@simon88 Hi there,
no, I don't have schematics yet, but you can easly check pinout labels in Cube MX.
This app is like one device is station set to RX, rest of them are sensors with different ID set to TX.
I this case lorawan gateway is device with station app.
I guess ping pong app is a bit different.

**Comment by polihedron** [comment]
base station:
![Zrzut ekranu 2023-07-14 085028](https://github.com/polihedron/Seeed-LoRa-E5_Point_to_Point_Phy_app/assets/46649005/2089aeab-3685-470d-8214-bd52c8e90953)
SPI:
![Zrzut ekranu 2023-07-14 085054](https://github.com/polihedron/Seeed-LoRa-E5_Point_to_Point_Phy_app/assets/46649005/9e1bdcc2-740b-4367-b95e-26ba6009660a)

Sensor:
![Zrzut ekranu 2023-07-14 085131](https://github.com/polihedron/Seeed-LoRa-E5_Point_to_Point_Phy_app/assets/46649005/0dd7d6f8-8ff6-48c6-8bdc-4b1a8dff2beb)

**Comment by simon88** [comment]
Perfect, thanks @polihedron
